= Introduction pratique à `git`
Stéphane Lopes <stephane.lopes@uvsq.fr>
v2021.01.1,
:toc: left
:toc-title: Sommaire
:sectanchors:
:sectlinks:
:sectnums:
:stem:
:icons: font
:source-highlighter: coderay

== Introduction
* `git` est un https://fr.wikipedia.org/wiki/Logiciel_de_gestion_de_versions[système de gestion de versions] distribué (VCS) libre
** chaque copie d'un dépôt `git` est elle-même un _dépôt_ qui peut être publié
* Il a été créé par _Linus Torvalds_ pour le développement du noyau Linux
* Il est utilisé par de nombreux projets (https://github.com/torvalds/linux[noyau Linux], https://github.com/Perl/perl5[interpréteur Perl], https://gitlab.gnome.org/GNOME[Gnome], https://git.samba.org/samba.git/[Samba], https://gitlab.freedesktop.org/xorg[X.org],…)

[NOTE]
====
* https://git-scm.com/[Site officiel] / https://git-scm.com/doc[Documentation]
* Aide-mémoire git/github (https://training.github.com/downloads/fr/github-git-cheat-sheet/[html] / https://training.github.com/downloads/fr/github-git-cheat-sheet.pdf[pdf])
* https://ndpsoftware.com/git-cheatsheet.html[Aide-mémoire visuel]
* https://www.atlassian.com/fr/git[Documentation] / https://www.atlassian.com/fr/dam/jcr:e7e22f25-bba2-4ef1-a197-53f46b6df4a5/SWTM-2088_Atlassian-Git-Cheatsheet.pdf[Git cheat sheet] (Atlassian)
====

== Concepts fondamentaux
=== Dépôt
* Un _dépôt_ `git` (_repository_) est un espace conservant l'ensemble d'un projet géré par `git`
** l'ensemble des données manipulées par `git` est conservé dans le répertoire `.git` au niveau de la racine du projet
* Un dépôt est constitué de plusieurs zones :
** l'_espace de travail_ ou _copie de travail_ (_workspace_) contient les documents modifiables par l'utilisateur,
** l'_index_ (_staging area_) enregistre les modifications qui feront partie de la prochaine version,
** le _dépôt_ (_repository_) conserve les versions successives du projet,
** la _remise_ (_stash_) permet de conserver temporairement des modifications.

NOTE: https://ndpsoftware.com/git-cheatsheet.html[Aide-mémoire visuel]

=== Les états d'un document
Un document peut se trouver dans 4 états :
[horizontal]
Validé:: (_committed_) conservé dans le dépôt
Modifié:: (_modified_}) modifié dans le répertoire de travail
Indexé:: (_staged_ ou _indexed_) prêt pour la validation
Remisé:: (_stashed_) mit de côté temporairement

=== Workflow de base
Après une étape de configuration initiale de `git` (à faire une unique fois après l'installation) et après la création du projet (à faire pour créer l'espace `git` du projet), l'utilisation de base de `git` comprend trois étapes :

. modifier la copie de travail,
. ajouter le ou les documents modifiés à l'index,
. valider l'ensemble des changements pour créer une nouvelle version.

== Configuration initiale de git
* Le comportement de `git` peut être adapté grâce à la commande https://git-scm.com/docs/git-config[`git config`]
* La configuration est conservée de façon :
** globale au système (`--system`),
** globale pour l'utilisateur (`--global`)
** ou spécifique au projet
* `git config --list  --show-origin` affiche la configuration courante et la provenance de chaque propriété
+
[source,bash]
----
$ git config --list --show-origin
file:/home/user/.gitconfig       core.pager=less
file:/home/user/.gitconfig       core.autocrlf=input
file:/home/user/.gitconfig       color.ui=auto
file:/home/user/.gitconfig       alias.ci=commit
[...]
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=true
[...]
----
* Avant la première utilisation de `git` sur un projet, chaque utilisateur définit au minimum son identité
+
[source,bash]
----
git config --global user.name "John Doe"
git config --global user.email johndoe@example.com
----

NOTE: https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup[First-Time Git Setup]

== Manipulations de base
=== Créer un espace pour un projet
Deux approches sont possibles pour créer localement un espace `git` pour un projet :

* initialiser un dépôt local (https://git-scm.com/docs/git-init[`git init`]) ou
* faire une copie d'un dépôt existant (https://git-scm.com/docs/git-clone[`git clone`]).

==== Initialiser un dépôt
* La commande https://git-scm.com/docs/git-init[`git init`] initialise un dépôt `git`
+
[source,bash]
----
$ mkdir mon-projet
$ cd mon-projet/
$ git init # le répertoire courant mon-projet devient un dépôt git
Dépôt Git vide initialisé dans /tmp/mon-projet/.git/
----
* Cette commande ajoute un répertoire `.git` à la racine du projet

==== Copier un dépôt existant
* La commande https://git-scm.com/docs/git-clone[`git clone`] effectue une copie d'un dépôt existant
+
[source,bash]
----
$ git clone https://github.com/libgit2/libgit2
Clonage dans 'libgit2'...
remote: Enumerating objects: 107280, done.
remote: Counting objects: 100% (107280/107280), done.
remote: Compressing objects: 100% (29501/29501), done.
remote: Total 107280 (delta 75854), reused 107277 (delta 75851), pack-reused 0
Réception d objets: 100% (107280/107280), 54.00 Mio | 19.16 Mio/s, fait.
Résolution des deltas: 100% (75854/75854), fait.
----
* Le clonage d'un dépôt distant peut utiliser les protocoles `https` ou `git` (avec `ssh`)

=== Apporter des modifications au projet
* Chaque modification doit être indexée par `git` avant d'être enregistrée dans une nouvelle version du projet
* Les commandes https://git-scm.com/docs/git-add[`git add`], https://git-scm.com/docs/git-rm[`git rm`] et https://git-scm.com/docs/git-mv[`git mv`] permettent d'enregistrer des modifications dans l'index
+
[source,bash]
----
$ git add index.adoc
----
* Un document peut être retiré de l'index avec la commande `git restore --staged`
+
[source,bash]
----
$ git restore --staged index.adoc
----

[IMPORTANT]
====
* Une commande de ce type doit être exécutée pour chaque modification devant apparaître dans la prochaine version
* Les documents produits à partir des sources du projet ne doivent pas être indexés (résultats d'une compilation, documentation générée, ...)
====

=== Consulter l'état des fichiers
* La commande https://git-scm.com/docs/git-status[`git status`] affiche l'état des documents  
+
[source,bash]
----
$ git status
Sur la branche main
Votre branche est en avance sur 'origin/main' de 1 commit.
  (utilisez "git push" pour publier vos commits locaux)

Modifications qui ne seront pas validées :
  (utilisez "git add <fichier>..." pour mettre à jour ce qui sera validé)
  (utilisez "git restore <fichier>..." pour annuler les modifications dans le répertoire de travail)
	modifié :         index.adoc

aucune modification n a été ajoutée à la validation (utilisez "git add" ou "git commit -a")
$ git add index.adoc
$ git status
Sur la branche main
Votre branche est en avance sur 'origin/main' de 1 commit.
  (utilisez "git push" pour publier vos commits locaux)

Modifications qui seront validées :
  (utilisez "git restore --staged <fichier>..." pour désindexer)
	modifié :         index.adoc
----
* L'option `--short` (ou `-s`) donne l'information de façon concise
+
[source,bash]
----
$ git status -s
 M index.adoc
----

=== Examiner les changements
La commande https://git-scm.com/docs/git-diff[`git diff`] affiche le détail des changements sur les fichiers.

* Sans option, les différences entre la copie de travail et l'index sont affichées
+
[source,bash]
----
$ git diff index.adoc
diff --git i/index.adoc w/index.adoc
index a82de36..6f14e19 100644
--- i/index.adoc
+++ w/index.adoc
@@ -12,28 +12,30 @@ v2021.01.1,
 
 == Introduction
+** chaque copie d un dépôt `git` est elle-même un _dépôt_ qui peut être publié
 * Il a été créé par _Linus Torvalds_ pour le développement du noyau Linux
-* Chaque copie de travail est elle-même un _dépôt_ qui peut être publié
[...]
@@ -55,74 +57,145 @@ Après une étape de configuration 
[...]
----
* L'option `--cached` effectue la comparaison entre l'index et le dernier commit
+
[source,bash]
----
$ git diff --cached index.adoc
diff --git c/index.adoc i/index.adoc
index a82de36..b307752 100644
--- c/index.adoc
+++ i/index.adoc
@@ -12,28 +12,30 @@ v2021.01.1,
[...]
----
* Il est également possible de comparer une révision particulière avec la copie de travail, deux révisions, ...

=== Créer une nouvelle version
* La commande https://git-scm.com/docs/git-commit[`git commit`] valide les modifications de l'index et crée une nouvelle version (_commit_)
** chaque commit est associé à un message (option `-m` de `git commit`)
+
[source,bash]
----
$ git commit -m"Ajoute des exemples aux différentes sections"
[main 8465838] Ajoute des exemples aux différentes sections
 1 file changed, 118 insertions(+), 27 deletions(-)
----
* L'option `-a` permet de valider tous les changements des fichiers déjà suivis sans `git add` préalable
* L'option `--amend` permet de modifier le dernier commit
+
CAUTION: Ne jamais modifier un commit qui a déjà été partagé avec un autre dépôt
+
[source,bash]
----
$ git add index.adoc
$ git commit -m"Ajoute des exemples aux différentes sections" --amend
[main 9c72c80] Ajoute des exemples aux différentes sections
 Date: Thu Jan 28 13:27:18 2021 +0100
 1 file changed, 148 insertions(+), 34 deletions(-)
----

=== Consulter l'historique des versions
* La commande https://git-scm.com/docs/git-log[`git log`] liste l'ensemble des révisions enregistrées
+
[source,bash]
----
$ git log
commit 9c72c80 (HEAD -> main)
Author: John Doe <john.doe@example.com>
Date:   Thu Jan 28 13:27:18 2021 +0100

    Ajoute des exemples aux différentes sections

commit 9b77d11
Author: John Doe <john.doe@example.com>
Date:   Thu Jan 28 11:00:12 2021 +0100

    Ignore les fichiers générés par asciidoctor
[...]
----
* L'option `-2` (ou `-n` avec n entier) limite aux n dernières
* `-p` affiche également les différences
* Le format de la sortie peut être adapté (`--pretty=oneline`, `--pretty=format:"..."`)
* `--graph` montre le graphe des branches et des fusions

NOTE: https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History[Viewing the Commit History]

=== Ignorer des fichiers
* Certains fichiers ne doivent pas être suivis (résultat de la compilation, fichiers temporaires d'un éditeur, ...)
* Un fichier https://git-scm.com/docs/gitignore[`.gitignore`] placé dans le projet (et dans le dépôt) permet de lister les fichiers et répertoires à ne pas suivre
* Des https://github.com/github/gitignore[exemples pour de nombreux types de projets] sont disponibles

NOTE: https://www.atlassian.com/fr/git/tutorials/saving-changes/gitignore[.gitignore]

=== Échanger des commits avec un autre dépôt
* La commande https://git-scm.com/docs/git-remote[`git remote`] permet de gérer les références à un dépôt distant
+
[source,bash]
----
# ajoute une référence origin vers un dépôt
$ git remote add origin https://github.com/libgit2/libgit2

# liste les références
$ git remote -v
origin	https://github.com/libgit2/libgit2 (fetch)
origin	https://github.com/libgit2/libgit2 (push)
----
+
IMPORTANT: La commande `git clone` ajoute automatiquement une référence nommée `origin` vers le dépôt source
* https://git-scm.com/docs/git-fetch[`git fetch`] récupère les révisions d'un autre dépôt
* https://git-scm.com/docs/git-pull[`git pull`] récupère les révisions et les intègre
* https://git-scm.com/docs/git-push[`git push`] envoie les révisions locales vers une référence
+
[source,bash]
----
$ git push origin main
Énumération des objets: 9, fait.
Décompte des objets: 100% (9/9), fait.
Compression par delta en utilisant jusqu'à 24 fils d'exécution
Compression des objets: 100% (5/5), fait.
Écriture des objets: 100% (6/6), 2.43 Kio | 2.43 Mio/s, fait.
Total 6 (delta 3), réutilisés 0 (delta 0), réutilisés du pack 0
remote: Resolving deltas: 100% (3/3), completed with 2 local objects.
To github.com:user/howto-git.git
   30fca42..9c72c80  main -> main
----
** l'option `-u` (`--set-upstream`) permet de ne plus préciser la référence et la branche pour les `push` suivants

== Branches
=== Branches
* Une _branche_ est une ligne de développement indépendante de la ligne principale mais qui partage le même historique
+
[ditaa, "git-branch",svg]
----
                           +-------+   +------+
                           | master|<--| HEAD |
                           | cRED  |   | cYEL |
                           +-------+   +------+
                               |
                               v
                           +-------+
                  +--------| 56GH8 |
                  |        |       |
                  v        +-------+
 +-------+    +-------+
 | 12CV5 |<---| 3A4E6 |
 |       |    |       |
 +-------+    +-------+
                  ^        +-------+
                  |        | 78BHD |
                  +--------|       |
                           +-------+
                               ^
                               |
                           +--------+
                           | testing|
                           | cRED   |
                           +--------+
----

* Une branche peut ensuite être fusionnée avec une autre afin d'y reporter les modifications

NOTE: https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell[Git Branching - Branches in a Nutshell], *Pro Git*, _Scott Chacon and Ben Straub_, Apress, 2014.

=== Manipulation de branches
* L'initialisation d'un dépôt crée une branche nommée _master_ par convention
+
[source,bash]
----
git init
----
* Création de la branche _testing_
+
[source,bash]
----
git branch testing
----
* Basculer sur la branche _testing_
+
[source,bash]
----
git checkout testing
----
* Création et bascule en une seule opération sur la branche _testing_
+
[source,bash]
----
git checkout -b testing
----
* Suppression de la branche _testing_
+
[source,bash]
----
git branch -d testing
----

WARNING: https://github.com/[Github] a https://github.com/github/renaming[modifié les conventions de nommage] de la branche principale qui se nomme `main` pour les nouveaux dépôts créés sur https://github.com/[Github].

=== Fusion de branches
* La _fusion_ permet de "reporter les changements d'une branche sur une autre.
+
[source,bash]
----
git checkout master
git merge testing
----
* La fusion peut provoquer des conflits

=== Tags
* Un _tag_ est un marqueur qui fait référence à une révision particulière
* Lister les tags
+
[source,bash]
----
git tag
----
* Placer un tag sur la révision courante (_HEAD_)
+
[source,bash]
----
git tag -a v1.0 -m"Version 1.0"
----
* Envoyer le tag _v1.0_ sur le dépôt _origin_
+
[source,bash]
----
git push origin v1.0
----
* Envoyer tous les tags sur le dépôt _origin_
+
[source,bash]
----
git push origin --tags
----
* Se positionner sur le tag _v1.0_
+
[source,bash]
----
git checkout -b version1 v1.0
----

== Workflows
=== Workflows avec git
* Un _workflow_ décrit un ensemble d'activités ainsi que la manière dont elles s'enchaînent
* Un workflow git décrit:
** la façon d'utiliser les branches,
** quand et comment les fusionner.

=== Workflow centralisé
* C'est le workflow le plus simple et le plus proche de celui des VCS centralisés
* Un dépôt fait référence
* Tout se passe sur la branche principale (_master_)
* Quand l'historique local est satisfaisant, il est publié sur le dépôt de référence
* En cas de conflit, les modifications distantes sont reportées localement (_rebase_)
* L'historique est toujours linéaire

NOTE: https://www.atlassian.com/fr/git/tutorials/comparing-workflows#centralized-workflow[Centralized workflow], Atlassian Git Tutorial

=== Workflow _une branche par fonctionnalité_
* Chaque développement se déroule sur une branche spécifique (_feature branch_)
* La branche principale (_master_) ne contient que du code \og fiable\fg{}
* Un dépôt fait référence
* Les _feature branches_ sont poussées sur le dépôt central
* Quand les modifications sont satisfaisantes, la feature branch est fusionnée avec _master_
* Il est possible d'utiliser les _pull requests_ pour discuter d'une branche spécifique

NOTE: https://www.atlassian.com/fr/git/tutorials/comparing-workflows/feature-branch-workflow[Feature branch workflow], Atlassian Git Tutorial
