= Introduction pratique à `git`
Stéphane Lopes <stephane.lopes@uvsq.fr>
v2021.01.1,
:toc: left
:toc-title: Sommaire
:sectanchors:
:sectlinks:
:sectnums:
:stem:
:icons: font
:source-highlighter: coderay

== Introduction
* `git` est un https://fr.wikipedia.org/wiki/Logiciel_de_gestion_de_versions[système de gestion de versions] distribué (VCS) libre
* Il a été créé par _Linus Torvalds_ pour le développement du noyau Linux
* Il est utilisé par de nombreux projets (https://github.com/torvalds/linux[noyau Linux], https://github.com/Perl/perl5[interpréteur Perl], https://gitlab.gnome.org/GNOME[Gnome], https://git.samba.org/samba.git/[Samba], https://gitlab.freedesktop.org/xorg[X.org],…)
* Chaque copie de travail est elle-même un _dépôt_ qui peut être publié

[TIP]
====
* https://git-scm.com/[Site officiel] / https://git-scm.com/doc[Documentation]
* Aide-mémoire git/github (https://training.github.com/downloads/fr/github-git-cheat-sheet/[html] / https://training.github.com/downloads/fr/github-git-cheat-sheet.pdf[pdf])
* https://ndpsoftware.com/git-cheatsheet.html[Aide-mémoire visuel]
* https://www.atlassian.com/fr/git[Documentation] (Atlassian)
====

== Concepts fondamentaux
=== Dépôt
* Un _dépôt_ `git` (_repository_) est un espace conservant l'ensemble d'un projet géré par `git`
** l'ensemble des données manipulées par `git` est conservé dans le répertoire `.git` qui se trouve au niveau de la racine du projet
* Un dépôt est constitué de plusieurs zones :
** l'_espace de travail_ ou _copie de travail_ (_workspace_) contient les documents modifiables par l'utilisateur,
** l'_index_ (_staging area_) enregistre les modifications qui feront partie de la prochaine version,
** le _dépôt_ (_repository_) conserve les versions successives du projet,
** la _remise_ (_stash_) permet de conserver temporairement des modifications.

=== Les états d'un document
Un document peut se trouver dans 4 états :
[horizontal]
Validé:: (_committed_) conservé dans le dépôt
Modifié:: (_modified_}) modifié dans le répertoire de travail
Indexé:: (_staged_ ou _indexed_) prêt pour la validation
Remisé:: (_stashed_) mit de côté temporairement

=== Workflow de base
Après une étape de configuration initiale de `git` (à faire une unique fois après l'installation) et après la création du projet (à faire pour créer l'espace `git` du projet), l'utilisation de base de `git` comprend trois étapes :

. modifier la copie de travail,
. ajouter le ou les documents modifiés à l'index,
. valider l'ensemble des changements pour créer une nouvelle version.

== Configuration initiale de git
* Le comportement de `git` peut être adapté grâce à la commande https://git-scm.com/docs/git-config[`git config`]
* La configuration est conservée de façon :
** globale au système (`--system`),
** globale pour l'utilisateur (`--global`)
** ou spécifique au projet
* `git config --list` affiche la configuration courante
* Avant la première utilisation de `git` sur un projet, chaque utilisateur définit au minimum son identité

.Configuration intiale de `git`
[source,bash]
----
git config --global user.name "John Doe"
git config --global user.email johndoe@example.com
----

== Créer un espace pour un projet
Deux approches sont possibles pour créer localement un espace `git` pour un projet :

* initialiser un dépôt local (https://git-scm.com/docs/git-init[`git init`]) ou
* faire une copie d'un dépôt existant (https://git-scm.com/docs/git-clone[`git clone`]).

=== Initialiser un dépôt
.dans le répertoire `mon-projet`
[source,bash]
----
mkdir mon-projet
cd mon-projet/
git init
----

=== Copier un dépôt existant
* le clonage d'un dépôt distant peut utiliser les protocoles `https` ou `git` (avec `ssh`)

[source,bash]
----
git clone https://github.com/libgit2/libgit2
----

== Consulter l'état des fichiers
* La commande https://git-scm.com/docs/git-status[`git status`] affiche l'état des documents  
* L'option `--short` (ou `-s`) donne l'information de façon concise

== Ajouter des modifications dans l'index
* Les commande https://git-scm.com/docs/git-add[`git add`], https://git-scm.com/docs/git-rm[`git rm`] et https://git-scm.com/docs/git-mv[`git mv`] permettent d'enregistrer des modifications dans l'index

WARNING: Une commande de ce type doit être exécutée pour chaque modification devant apparaître dans la prochaine version

== Examiner les changements
* La commande https://git-scm.com/docs/git-diff[`git diff`] affiche le détail des changements sur les fichiers
* Sans option, les différences entre la copie de travail et l'index sont affichées
* L'option `--cached` effectue la comparaison entre l'index et le dernier commit
* Il est également possible de comparer une révision particulière avec la copie de travail, deux révisions, ...

== Créer une nouvelle version
* La commande https://git-scm.com/docs/git-commit[`git commit`] valide les modifications de l'index et crée une nouvelle version (_commit_)
* Chaque commit est associé à un message (option `-m` de `git commit`)
* L'option `-a` permet de valider tous les changements des fichiers déjà suivis sans `git add` préalable

== Ignorer des fichiers
* Certains fichiers ne doivent pas être suivis
** résultat de la compilation
** fichiers temporaires d'un éditeur
* Un fichier https://git-scm.com/docs/gitignore[`.gitignore`] placé dans le projet (et dans le dépôt) permet de lister les fichiers et répertoires à ne pas suivre
* Des \href{https://github.com/github/gitignore}{exemples pour de nombreux types de projets} sont disponibles

== Consulter l'historique
* La commande https://git-scm.com/docs/git-log[`git log`] liste l'ensemble des révisions enregistrées
* L'option `-2` (ou `-n` avec n entier) limite aux n dernières
* `-p` affiche également les différences
* Le format de la sortie peut être adapté (`--pretty=oneline, `--pretty=format:"..."`)
* `--graph` montre le graphe des branches et des fusions

== Échanger des commits avec un autre dépôt
* La commande https://git-scm.com/docs/git-remote[`git remote`] permet de gérer les références à un dépôt distant
+
[source,bash]
----
# ajoute une référence origin vers un dépôt
git remote add origin https://github.com/libgit2/libgit2

# liste les références
git remote -v
----
* `git fetch` récupère les révisions des dépôts référencés
* `git pull` récupère les révisions et les fusionne
* `git push` envoie les révisions locales vers une référence
+
[source,bash]
----
git push -u origin master
----

== Branches
=== Branches
* Une _branche_ est une ligne de développement indépendante de la ligne principale mais qui partage le même historique
+
[ditaa, "git-branch",svg]
----
                           +-------+   +------+
                           | master|<--| HEAD |
                           | cRED  |   | cYEL |
                           +-------+   +------+
                               |
                               v
                           +-------+
                  +--------| 56GH8 |
                  |        |       |
                  v        +-------+
 +-------+    +-------+
 | 12CV5 |<---| 3A4E6 |
 |       |    |       |
 +-------+    +-------+
                  ^        +-------+
                  |        | 78BHD |
                  +--------|       |
                           +-------+
                               ^
                               |
                           +--------+
                           | testing|
                           | cRED   |
                           +--------+
----

* Une branche peut ensuite être fusionnée avec une autre afin d'y reporter les modifications

NOTE: https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell[Git Branching - Branches in a Nutshell], *Pro Git*, _Scott Chacon and Ben Straub_, Apress, 2014.

=== Manipulation de branches
* L'initialisation d'un dépôt crée une branche nommée _master_ par convention
+
[source,bash]
----
git init
----
* Création de la branche _testing_
+
[source,bash]
----
git branch testing
----
* Basculer sur la branche _testing_
+
[source,bash]
----
git checkout testing
----
* Création et bascule en une seule opération sur la branche _testing_
+
[source,bash]
----
git checkout -b testing
----
* Suppression de la branche _testing_
+
[source,bash]
----
git branch -d testing
----

WARNING: https://github.com/[Github] a https://github.com/github/renaming[modifié les conventions de nommage] de la branche principale qui se nomme `main` pour les nouveaux dépôts créés sur https://github.com/[Github].

=== Fusion de branches
* La _fusion_ permet de "reporter les changements d'une branche sur une autre.
+
[source,bash]
----
git checkout master
git merge testing
----
* La fusion peut provoquer des conflits

=== Branches distantes
* Une branche distante fait référence a une branche dans un dépôt distant
* `git clone` crée automatiquement le dépôt _origin_
* La commande `git remote` permet de gérer les dépôts distants
* Récupérer les modifications d'une branche distante
+
[source,bash]
----
git fetch origin
----
* Envoyer les modifications sur une branche distante
+
[source,bash]
----
git push origin master
----
* Récupérer et fusionner les modifications d'une branche distante
+
[source,bash]
----
git pull origin master
----

=== Tags
* Un _tag_ est un marqueur qui fait référence à une révision particulière
* Lister les tags
+
[source,bash]
----
git tag
----
* Placer un tag sur la révision courante (_HEAD_)
+
[source,bash]
----
git tag -a v1.0 -m"Version 1.0"
----
* Envoyer le tag _v1.0_ sur le dépôt _origin_
+
[source,bash]
----
git push origin v1.0
----
* Envoyer tous les tags sur le dépôt _origin_
+
[source,bash]
----
git push origin --tags
----
* Se positionner sur le tag _v1.0_
+
[source,bash]
----
git checkout -b version1 v1.0
----

== Workflows
=== Workflows avec git
* Un _workflow_ décrit un ensemble d'activités ainsi que la manière dont elles s'enchaînent
* Un workflow git décrit:
** la façon d'utiliser les branches,
** quand et comment les fusionner.

=== Workflow centralisé
* C'est le workflow le plus simple et le plus proche de celui des VCS centralisés
* Un dépôt fait référence
* Tout se passe sur la branche principale (_master_)
* Quand l'historique local est satisfaisant, il est publié sur le dépôt de référence
* En cas de conflit, les modifications distantes sont reportées localement (_rebase_)
* L'historique est toujours linéaire

NOTE: https://www.atlassian.com/fr/git/tutorials/comparing-workflows#centralized-workflow[Centralized workflow], Atlassian Git Tutorial

=== Workflow _une branche par fonctionnalité_
* Chaque développement se déroule sur une branche spécifique (_feature branch_)
* La branche principale (_master_) ne contient que du code \og fiable\fg{}
* Un dépôt fait référence
* Les _feature branches_ sont poussées sur le dépôt central
* Quand les modifications sont satisfaisantes, la feature branch est fusionnée avec _master_
* Il est possible d'utiliser les _pull requests_ pour discuter d'une branche spécifique

NOTE: https://www.atlassian.com/fr/git/tutorials/comparing-workflows/feature-branch-workflow[Feature branch workflow], Atlassian Git Tutorial
