name: Build with Asciidoctor and deploy on gh-pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Run bundler and asciidoctor
        run: |
          gem install bundler
          bundle install
          asciidoctor -r asciidoctor-diagram -D html index.adoc
      - name: Deploy on gh-pages
        uses: NickSchimek/deploy_jamstack_action@v1
        with:
          build-dir: html
